### ISSUE TITLE
Not working with latest training file

### ISSUE THREAD

**Issue by thomasegense** [emara-geek/object-recognition-tensorflow#1]
Working with Inception v3.0, but not with latest training data-file:
https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz

And thanks for upgrading from inception h5 to v3.0 btw.

**Comment by tahaemara** [comment]
You can rename the two inceptions files form “inception_v3_2016_08_28_frozen.pb”  to  “tensorflow_inception_graph.pb” and from ”imagenet_slim_labels.txt” to “imagenet_comp_graph_label_strings.txt” or just rename these lines (123 & 124) to the new names of files. 
https://github.com/emara-geek/object-recognition-tensorflow/blob/master/src/main/java/com/emaraic/ObjectRecognition/Recognizer.java#L123

**Comment by thomasegense** [comment]
I tried that of course :) 
The error is: Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No Operation named [DecodeJpeg/contents] in the Graph

They have changed something behind the scenes just as from h5 to v3.0

**Comment by thomasegense** [comment]
Also makes no difference if I upgrade to latests:
   
    
 <dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow</artifactId>
  <version>1.2.0-rc1</version>
</dependency>

**Comment by thomasegense** [comment]
Also makes no difference if I upgrade to latest tensorflow(1.2.0-rc1), still same bug.
Could be the training file that is corrupt somethow.

1.2.0-rc1

**Comment by tahaemara** [comment]
Change the name of the input and out layer at line 173 
https://github.com/emara-geek/object-recognition-tensorflow/blob/master/src/main/java/com/emaraic/ObjectRecognition/Recognizer.java#L173
                   to 
` Tensor result = s.runner().feed("input", image).fetch("InceptionV3/Predictions/Reshape_1").run().get(0)) `

This also generates an error "Exception in thread "AWT-EventQueue-0" org.tensorflow.TensorFlowException: Output 0 of type string does not match declared output .....", I am working on solving it.
